### ISSUE TITLE
Unable to set timezone for events

### ISSUE THREAD

**Issue by nabrams** [jasonleibowitz/react-add-to-calendar-hoc#3]
# Bug report

## Describe the bug

By formatting each datetime in .utc(), it sets the event to be the time of the local browser. I want to be able to set the date in eastern standard time so that customers booking an appointment out of state do not book the wrong time. 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. when setting the start and end times in {event}

  const startDatetime = moment(slot.time)
    .utc()
    .format("YYYYMMDDTHHmmssZ");

2.if I do not include .utc() per your examples, the date is formatted wrong and will not work when trying to add the event to any of the calendars. 

## Expected behavior
I am expecting to be able to specify a timezone. 

## System information
 - OS: [e.g. macOS]
 - Browser [chrome]
 - Version of Library: [e.g. 1.0.3]

**Comment by AndrewNatoli** [comment]
@nabrams I'm not fully understanding what you mean. 

Are you, for example, saying an event is 9:00am but someone in the Pacific time zone is getting 7:00am? Or is it interpreting 9:00am as UTC+/- 0 and they're getting 2:00am?

If it's the latter, I've had success specifying the timezone in my date string like this: `2018-08-27 16:30:00-04:00`

**Comment by AndrewNatoli** [comment]
Nevermind my previous (now deleted) comment; I noticed my timezones were off too. I'll let you know if I find a workaround :)

**Comment by AndrewNatoli** [comment]
@nabrams I messed with this a bit more and realized my timezones were actually working. 😅 

So to fully understand, are you having an issue where you're making an event that's, for example, 9am in your time zone but people three hours behind are also seeing 9am? 

I've had luck passing in a time like: `2018-08-07 18:00:00-04:00` and not calling `utc()` anywhere. I end up with proper timezone-adjusted times after that, except for when the timezone ends up being in a different calendar date. That issue I'll probably be looking into tomorrow.

**Comment by jasonleibowitz** [comment]
Are you saying that you want the calendar event to _include_ timezone information rather than just adjust the time. For instance, for an appointment at `5pm on Jan 10, 2018` in New York you want a user in LA who adds it to have an event that reads `Jan 10, 2018 5pm EST` rather than `Jan 10, 2018 2pm`?

I found this [forum post](https://productforums.google.com/forum/#!topic/calendar/u6s8bzwL5Mc) that seems to answer the question of how to do this on Google Calendar. There's another query param to specify timezone: `&ctz=America/Los_Angeles`. 

It looks like you still have to use UTC/convert the date to the proper timezone before passing into the URL, but at least `ctz` lets you specify the time zone.

I probably won't have time to work on this until the weekend. If one of you guys have time, feel free to make a PR.

**Comment by jasonleibowitz** [comment]
@nabrams Sorry for the long delay. Just committed #15 which solves your issue. I added an example to the demo page that shows how to properly handle timezones. 

Let me know if you're still having issues.

**Comment by jasonleibowitz** [comment]
FYI just published v1.0.7 that includes better timezone support with better docs.
