### ISSUE TITLE
Allow Optional Location and Start/End Dates

### ISSUE THREAD

**Issue by robert-claypool** [jasonleibowitz/react-add-to-calendar-hoc#31]
## Feature request

In some cases, I would like to exclude location and dates from the calendar event (user can enter them manually after the event is passed to Google, iCal, or other calendar).

Is this something you considered but decided not to do? I know that Google accepts event URLs without `location` or `dates` query params. I have not tested other calendars, but if you think they would work, I can issue a PR for this change.

**Comment by jasonleibowitz** [comment]
Sorry for the delayed response. Location is an optional property, so you definitely don't have to pass that in with the current implementation. Start and End datetime aren't required by google, but I didn't see a use-case where someone would want to create a calendar link _without_ dates. When you do that the event google creates defaults to an all day event for today. I also didn't check to see if an event without dates would be valid for iCal, Outlook and Yahoo. 

If you want to create a PR, we can definitely add that in provided it doesn't break any existing functionality. Otherwise I can look at this over the holiday if you still find it useful.

**Comment by doublejosh** [comment]
It would be nice if the required fields on the event object were documented. Took a while to figure this out.
